# Generated by Django 4.1.6 on 2023-02-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loading_doc',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
